name: policy-checks

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: open-policy-agent/setup-opa@v1
        with:
          version: latest
      - name: Format
        run: opa fmt policies/**/*.rego tests/**/*.rego --check
      - name: Check
        run: opa check policies tests
      - name: Test
        run: opa test policies tests
